version: '3'

tasks:

  default:
    deps: [main]

  main:
    cmds:
     - zig build
    #  - wasm2wat zig-out/lib/math.wasm -o math.wat
     - bun index.ts

  clean:
    aliases: ['c']
    cmds:
      - rm -rf .zig-cache
      - rm -rf zig-out
      - rm -rf math.wasm
      - rm -rf math.wasm.o
      - rm -rf math.wat