version: '3'

tasks:

  default:
    deps: [main]

  main:
    cmds:
     - zig build
     - wasm2wat zig-out/lib/math.wasm -o math.wat

  fib:
    cmds:
     - zig build-exe src/fibonacci.zig -target wasm32-freestanding -rdynamic
     - wasm2wat fibonacci.wasm -o fib.wat
     
  clean:
    aliases: ['c']
    cmds:
      - rm -rf .zig-cache
      - rm -rf zig-out
      - rm -rf math.wasm
      - rm -rf math.wasm.o
      - rm -rf math.wat